### PR TITLE
Adds the original textures around forests and in some doorways which …

### PR DESCRIPTION
**Pull request by SaulMyers**
…darken them, and includes a pixel shader to fade them out as the player approaches. Added specifically for Gothic but doesn't seem to impact Gothic II.

### CODE REVIEW

**Comment by ThielHater** [comment]
Please do not treat OWODWFALL_STONE_A0 and OWODWFALL_HITSURFACE_A0 as portals, just render them properly with zMAT_ALPHA_FUNC_BLEND.

**Comment by SaulMyers** [comment]
> Please do not treat OWODWFALL_STONE_A0 and OWODWFALL_HITSURFACE_A0 as portals.
> 
> **Edit:** I investigated the waterfall issue myself and opened a pull request (#110).

Agreed, I should not be treating those 2 as portals and I've removed that code. But the reason I removed the alpha blending on the waterfalls is that it causes issues with the display of the forest / doorway portals. See this for an example - it messes up fogging when looking out from inside specific places inside forests / doorways. Not everywhere, just a few places - I don't know why this is, but when I debugged it, it seemed that those waterfall textures were the cause. And indeed, with alpha blending turned off for those textures, the issue does not occur.

Example of the problem: https://easyupload.io/usmkpz

I personally think the waterfalls look better without the blending anyway - it's how the original waterfalls looked. And it also depends on the texture pack you're using of course.

I'm having another look into this issue though because it doesn't make any sense.

**Comment by ThielHater** [comment]
You are right, I was able to reproduce this behavior. I took a look at D3D11PFX_HeightFog::Render() but couldn't find the problem, yet.

**Comment by ThielHater** [comment]
How on earth did you figure that out? Even now that I know the part of the code, I still don't understand it. 😃

Alpha blending is hard, it seems like the renderer has a bunch of problems with it. If you can not figure out a solution, feel free to render the waterfall foam with alpha testing.

**Comment by SaulMyers** [comment]
Yes it is hard, and my coding background is superannuation so that's not helping 😂

I haven't figured out why it flips out when alpha blending is enabled but I think it has something to do with the shader engine... maybe? What I've found is that if I apply my new shader for forest portals to the waterfall foam, then I can enable alpha blending and it doesn't mess up the rendering of the fog.

I have no idea why and I'm sure I tried that before - I've also assigned the foam a new material group so maybe that's changing the behavior. Anyway this might do the trick, I just need to write a new shader for waterfalls and see if I can get it looking decent. This is how it looks re-using the forest portal shader - a bit odd but promising:

image

**Comment by ThielHater** [comment]
What I want to avoid, is that the waterfall foam behaves like a portal, making it invisible if you get close to it. If they need their own shader to be rendered with alpha blending and avoid flickering of the fog, then let's go this way.

**Comment by SaulMyers** [comment]
Well the fog flickering returned when I assigned the waterfall its own shader so that was a hint that the hack-ey way I was trying to switch shaders within the DrawMeshInfoListAlphablended was causing the issue. So now I'm building a separate list of alpha meshes for each type (world, portal, waterfall) and calling the DrawMeshInfoListAlphablended separately for each of those types, and it's working well. It doesn't seem to be causing a performance issue but I should check that.

So now I just need to write a waterfall foam shader that looks decent - this is what I have so far, which creates an effect very similar to the original engine.

image

**Comment by SaulMyers** [comment]
@lucifer602288 @ThielHater please test out this latest version when you have a chance, see the commit comment for details. The shader I've written for the waterfall foam is just a slightly altered copy of the existing alpha blend shader - pretty boring but very close to the original look of the waterfalls. If I have time one day I might see if I can make that shader a bit more interesting but my shader knowledge is very limited.

Thanks to you both for helping me with this.

**Comment by ThielHater** [comment]
I have tested it and two suggestions:

1. Please do not manipulate the alpha channel in PS_WaterfallFoam too much. You have set alpha blending in the code but then turned it to alpha testing in the shader with a very low opacity. This could be a compromise: color *= float4(1.0f, 1.0f, 1.0f, 0.66f)
2. The waterfall foam brightness is not yet affected by the day-night cycle.

**Comment by ThielHater** [comment]
Why are we not using the fog color that Gothic calculates?

To be honest, drawing the portals is closer to the original but I didn't miss them. Can we control this via UserSettings.ini? It should be easy to copy and paste the code related to "Draw Fog" for this.

**Comment by SaulMyers** [comment]
I fixed all of the stuff requested but I can't push it because of a conflict with #110 - why was that merged in before I got to finish what I was doing?

I fucking hate git.

**Comment by SaulMyers** [comment]
I seem to have gotten my changes pushed but a whole lot of other stuff was included due to me being forced to pull before I could push, e.g:
image

I don't know what happened and am too tired to care.

**Comment by ThielHater** [comment]
I am sorry to say but you messed up while merging. Git is hard to learn and even harder to master, next time try rebase. 😄

Maybe Keks1 will edit the PR and fix this?

**Review by lucifer602288 — APPROVED** [review]

**Review by lucifer602288 — APPROVED** [review]
Deleted some files to merge dueto this would set the GD3D11 project to an older state. I just saw that this has a direct effect on your @SaulMyers` repository. This was not meant this way. Please do a Sync Fork to fetch the latest status of Kirides` GD3D11 repository.

**Review by lucifer602288 — CHANGES_REQUESTED** [review]
Please delete from your pull request the files which are set here on deleted and as well the two binary files from the bottom. The list is as well above the previous comment. I am unfortunately not able to select which file to merge and which not.

**Comment by SaulMyers** [comment]
I haven't worked as a dev for years but yep, this is my memory of git. A confusing shit show.

I don't have time to learn new tricks so I just deleted the fork and started again - new pull request with everything in it here: #112

**Pull request closed without merging**
