### PR TITLE
Save settings: ShadowStrength, ShadowAOStrength, WorldAOStrength

### PR DESCRIPTION
**Pull request by vschmidt91**
Added three additional settings to be synced with the UserSettings.ini

(Personally I like pitch black nights)

### CODE REVIEW

**Comment by Kirides** [comment]
These kind of settings manipulate the overall lightning.
It would be better if they were put in the per-World settings aswell.

This way you can have different values depending on if you are in a pitch black cave-level (e.g. oldmine) or in the addonworld.

Places to change are
`GothicAPI::LoadRendererWorldSettings`
and
`GothicAPI::SaveRendererWorldSettings`

**Comment by vschmidt91** [comment]
Okay, the settings have been transferred to

GothicAPI::LoadRendererWorldSettings
and
GothicAPI::SaveRendererWorldSettings

Only tested in Gothic 1 with World and OldMine - seems to work fine though.

**Comment by Kirides** [comment]
@vschmidt91 can you rebase on current master and fix the merge conflict?
i would merge the PR then.

**Comment by pm4rcin** [comment]
@vschmidt91 any chance to rebase the PR?

**Comment by kirides** [comment]
Closed due to inactivity

**Pull request closed without merging**
