### PR TITLE
A new option under 'General' called 'DrawWeaponTrails'

### PR DESCRIPTION
**Pull request by SaulMyers**
This allows the poly strip weapon trails to be toggled on/off.

### CODE REVIEW

**Comment by kirides** [comment]
How is this different from Gothic.ini ?
```ini
[GAME]
zShowWeaponTrails=1
```

**Comment by SaulMyers** [comment]
That doesn't turn off the trails on arrows, just swords.

**Comment by kirides** [comment]
I see.
But we can not simply disable weapon trails alltogether, as that would also include spells like fireball etc. which would then (again) look ugly and not match the original game.

best would be, if it was possible (with perf in mind) to selectively disable certain trails.

**Comment by SaulMyers** [comment]
Ah I see, sorry I didn't realise spells used these trails too. I'd assumed that was the particle system but you're right, it does disable them and that's no good.

You can ignore this pull request then 😁

**Pull request closed without merging**
